server.port=8020
spring.application.name=vm3-spring-gateway
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
ai.service.base-url=${AI_SERVICE_URL:http://ai-service:8010}
integrations.vm1-base-url=${VM1_BASE_URL:http://65.52.207.139}
integrations.vm2-base-url=${VM2_BASE_URL:http://34.122.37.25}
integrations.vm2-jwt-token=${VM2_JWT_TOKEN:}
